### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by boarder2** [boarder2/Latest-Chatty-8#1]
Add some hotkey support!
- Next/Previous in thread list
- Next/Previous in single thread view
- Mark all threads / mark all posts in single thread read
- Refresh/resort
- Reply to currently viewed post

**Comment by bhaigh** [comment]
I like the idea of modeling the hotkeys off of Gmail.  Obviously all of these are not one-to-one with Latest Chatty in mind but maybe the broad strokes will work.  Things like k/j, o and p/n.

![image](https://cloud.githubusercontent.com/assets/125315/9186655/932f199a-3f95-11e5-9e31-cd753752c042.png)

**Comment by bhaigh** [comment]
I like the idea of modeling the hotkeys off of Gmail. Obviously all of these are not one-to-one with Latest Chatty in mind but maybe the broad strokes will work. Things like:

u : Back to threadlist
k / j : Newer/older conversation
o or <Enter> :  Open conversation; collapse/expand conversation
p / n : Read previous/next message
c : Compose
/ : Search
r :     Refresh
g then c :  Go to Chatty
g then M : Go to Shack Messages
