### ISSUE TITLE
Search Features and Shortcuts

### ISSUE THREAD

**Issue by zakfrazier** [boarder2/Latest-Chatty-8#60]
Would be great if on the left side there was a magnifying glass icon which when clicked gave the following options:
- My Posts
- My comments about...
- Replies to My Posts
- Vanity Search
- Advanced Search (this would open up a new section for advanced searching like root posts and whatnot.

Example of what Lamp has:
![capture](https://cloud.githubusercontent.com/assets/13838616/16317550/ac1e697e-3959-11e6-9608-1149dec45a95.PNG)

**Comment by boarder2** [comment]
Duplicate of Issue #5, but we'll keep this one around since it's more descriptive.

**Comment by boarder2** [comment]
This has been implemented in recent updates
